<a href="https://colab.research.google.com/github/TarunReddy77/Jovian-GANs/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('01-tensor-operations')
jovian.set_colab_id('1kpW_OBEWNygF_e3D4DnKF2pLkaOfB9CP')

     |████████████████████████████████| 68 kB 3.1 MB/s 


# 5 cool PyTorch functions that are good to know!

Pytorch is one of the most popular Deep Learning libraries used globally, packed with a ton of extremely useful functionality that comes built-in and is very easy to use. Most of the functions are frequently used by the Data Science community and hence are an integral part of the library. 

In this notebook, we will be looking at the following 5 interesting functions in the PyTorch library.

- polar
- full_like
- bernoulli
- topk
- combinations

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.polar

The **torch.polar** function is used to create a tensor of **polar complex numbers**. It takes two tensors as arguments. The first contains the **magnitudes** of the complex numbers to be generated, while the second one contains the **angles**.

The function zips the two tensors together, creating complex numbers by taking the magnitude from tensor 1 and angle from tensor 2.

For example, the complex number at index k is generated by zipping the numbers at index 2 in the magnitude and angle tensors like;

####**c[k] = a[k]cos(b[k]) + i(a[k]sin(b[k]))**,

where **a[k]** is the tensor of magnitudes, **b[k]** is the tensor of angles and **c[k]** is the resultant tensor of polar complex numbers.

Let's create a complex 1-dimensional tensor using the function.

In [ ]:
# Example 1
magnitudes = torch.tensor([1., 2])
angles = torch.tensor([0.25, 0.5])

complex_nums = torch.polar(magnitudes, angles)
complex_nums

tensor([0.9689+0.2474j, 1.7552+0.9589j])

That worked! Let's see if we could extend this to higher dimensions as well.

In [ ]:
# Example 2 - working
magnitudes = torch.tensor([[1, 2], [3, 4.]])
pi = np.pi
angles = torch.tensor([[pi/3, pi/2], [pi/4, pi/6]])

complex_nums = torch.polar(magnitudes, angles)
complex_nums

tensor([[ 5.0000e-01+0.8660j, -8.7423e-08+2.0000j],
        [ 2.1213e+00+2.1213j,  3.4641e+00+2.0000j]])

Now, let's see what happens if the pass data of different data types to the two constituent tensors.

In [ ]:
# Example 3 - breaking
magnitudes = torch.tensor([[5, 12], [3, 41]], dtype = torch.float32)
pi = np.pi
angles = torch.tensor([[pi/3, pi/2], [pi/4, pi/6]], dtype = torch.float64)

complex_nums = torch.polar(magnitudes, angles)
complex_nums

RuntimeError: ignored

Well, that didn't work! So, the torch.polar function expects the tensors to have the same data types.

This function is used to generate polar forms of complex numbers, which are frequently used in signal processing, which is closely related to machine learning.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/tarutornado/01-tensor-operations


'https://jovian.ai/tarutornado/01-tensor-operations'

## Function 2 - torch.full_like

This function is used to generate a tensor of same dimensions as the given tensor, but filled with the value provided. 

In the following example, we'll create a new tensor with the same dimensions as x.

In [ ]:
# Example 1 - working
x = torch.tensor([[1.,2],[3,4]])
y = torch.full_like(x,5)
y

tensor([[5., 5.],
        [5., 5.]])

We see that y is of same dimensions as x, but filled with the value 5. It also inferred the same datatype from x. 

Next, we'll try to explicitly mention the datatype of the new tensor.

In [ ]:
# Example 2 - working
x = torch.tensor([[1.,2],[3,4]])
y = torch.full_like(x,5, dtype = torch.int32)
y

tensor([[5, 5],
        [5, 5]], dtype=torch.int32)

Now, dtype is as we have instructed. Let us also see if the fill_value can be inferred by the example tensor, i.e, x. We'll not pass any fill_value.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([[1,1],[1,1]])
y = torch.full_like(x)
y

We observe that fill value is a required argument and can't be inferred from x, despite x being filled with just 1 value.

This function is extremely useful to create tensors that duplicate the dimensions of a particular tensor, but are initialized with a different value. It is especially used when the dimensions of the tensor to mimic are unknown.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/tarutornado/01-tensor-operations


'https://jovian.ai/tarutornado/01-tensor-operations'

## Function 3 - torch.bernoulli

This function is used to generate a tensor of binary numbers (i.e, 0s and 1s) using another tensor specifying the probabilities of choosing 1 in a bernoulli distribution.

It takes a tensor of probabilities as input and outputs a tensor of binary numbers of the same dimensions as the input.

In [ ]:
# Example 1 - working

a = torch.tensor([0.342, 0.765, 0.913, 0.245, 0.486])    #Let's create a tensor of probablities.
torch.bernoulli(a)

tensor([0., 0., 1., 1., 1.])

We see that as expected, high probabilities correspond to 1s and low end up in 0s. The last probability being close to 0.5, could have ended up almost equally likely in either 0 or 1.

In [ ]:
# Example 2 - working
a = torch.ones(3, 3)          # A tensor full of ones, implying that the probability of drawing "1" is 1
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In this example, the input tensor is full of ones. Therefore, the output tensor is also full of ones as the probability of choosing "0" is 0.

In [ ]:
# Example 3 - breaking
a = torch.tensor([0.5, 0.2, 1.2, 0.9, 0.6])
torch.bernoulli(a)

Here, the input tensor contains the value "1.2" at index "2", which is not a valid value for probability and therefore, the code breaks. Hence, we must ensure that all the values in the input tensor are in the range of 0 to 1 before feeding it to the torch.bernoulli function.

torch.bernoulli is used to generate a bernoulli distribution of binary numbers.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/tarutornado/01-tensor-operations


'https://jovian.ai/tarutornado/01-tensor-operations'

## Function 4 - torch.topk

torch.topk function is used to find the 'k' largest elements in a tensor, along with their indices. It takes a tensor and a number 'k' as arguments.

In [ ]:
# Example 1 - working
a = torch.linspace(-1, 1, steps=4)    # A tensor of 4 equally spaced values in the range of [-1, 1]
print(a)
torch.topk(a, 3)

tensor([-1.0000, -0.3333,  0.3333,  1.0000])


torch.return_types.topk(values=tensor([ 1.0000,  0.3333, -0.3333]), indices=tensor([3, 2, 1]))

As expected, the function returns the 3 largest numbers and their respective indices.

In [ ]:
# Example 2 - working
x = torch.rand(5,5)
print(x)
torch.topk(x, 3, largest = False)

tensor([[0.5462, 0.8178, 0.7260, 0.4542, 0.8448],
        [0.4933, 0.7005, 0.4082, 0.2119, 0.3228],
        [0.4206, 0.0257, 0.5467, 0.1597, 0.8954],
        [0.3538, 0.7061, 0.9137, 0.4475, 0.8264],
        [0.1262, 0.9585, 0.4828, 0.2721, 0.2207]])


torch.return_types.topk(values=tensor([[0.4542, 0.5462, 0.7260],
        [0.2119, 0.3228, 0.4082],
        [0.0257, 0.1597, 0.4206],
        [0.3538, 0.4475, 0.7061],
        [0.1262, 0.2207, 0.2721]]), indices=tensor([[3, 0, 2],
        [3, 4, 2],
        [1, 3, 0],
        [0, 3, 1],
        [0, 4, 3]]))

In this example, we pass a 5x5 array to the topk function, asking for the smallest three numbers (since largest = False) along each row (since dim = 0 by default).

We get the expected numbers along with their corresponding indices.

In [ ]:
# Example 3 - breaking
x = torch.arange(6.)     # A tensor of numbers in range [0,5]
print(x)
torch.topk(x,7)

In this example, we ask for '7' largest numbers in a tensor containing only '6' values. Hence, the code breaks.

This function is pretty useful when we are only interested in either the few largest or smallest numbers in a tensor, irrespective of its size.

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/tarutornado/01-tensor-operations


'https://jovian.ai/tarutornado/01-tensor-operations'

## Function 5 - torch.combinations
This function is used to generate a tensor of all combinations of size 'r' from a tensor. By default, it does it without replacements.

In [ ]:
# Example 1 - working
a = torch.tensor([1,2,3,4])
torch.combinations(a,3)

tensor([[1, 2, 3],
        [1, 2, 4],
        [1, 3, 4],
        [2, 3, 4]])

It generated the 4 possible combinations of 3 elements from the given tensor as expected.

In [ ]:
# Example 2 - working
a = torch.tensor([1,2,3])
torch.combinations(a,2, with_replacement = True)

tensor([[1, 1],
        [1, 2],
        [1, 3],
        [2, 2],
        [2, 3],
        [3, 3]])

Now, with 'with_replacement' parameter set to True, we see that replacements are allowed, giving many more combinations.

In [ ]:
# Example 3 - breaking
a = torch.tensor([[1,2,3], [4,5,6]])
torch.combinations(a,2)

Here, when we provided a multi-dimensional vector as input, it is ambiguous as to how to choose elements for combinations, and hence, the code breaks.

This function is very useful to create all possible combinations of elements present in the input tensor, which is a common use case in discrete math. 

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/tarutornado/01-tensor-operations


'https://jovian.ai/tarutornado/01-tensor-operations'

## Conclusion

In this notebook, we had a sneak peek at 5 cool and useful functions in PyTorch. These functions are pretty useful for programmers working in Machine Learning to quickly generate the data in the way they want without worrying about the underlying logic involved.

There are many more such functions in PyTorch, which can be explored in the PyTorch documentation, the link to which is provided below. Keep exploring!

## Reference Link
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/tarutornado/01-tensor-operations


'https://jovian.ai/tarutornado/01-tensor-operations'

In [ ]:
jovian.submit(assignment="zerotogans-a1")

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
Committed successfully! https://jovian.ai/tarutornado/01-tensor-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor
